/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

// You should NOT make any changes in this file as it will be overwritten.

// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoreTeamRouteImport } from './routes/core-team'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminActivitiesRouteImport } from './routes/_authenticated/admin.activities'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminContactMessagesRouteImport } from './routes/_authenticated/admin.contact-messages'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminCoreTeamRouteImport } from './routes/_authenticated/admin.core-team'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminJoinApplicationsRouteImport } from './routes/_authenticated/admin.join-applications'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminVolunteersRouteImport } from './routes/_authenticated/admin.volunteers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)

const CoreTeamRoute = CoreTeamRouteImport.update({
  id: '/core-team',
  path: '/core-team',
  getParentRoute: () => rootRouteImport,
} as any)

const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)

const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)

const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)

const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAdminActivitiesRoute =
  AuthenticatedAdminActivitiesRouteImport.update({
    id: '/admin/activities',
    path: '/admin/activities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/admin/applications',
    path: '/admin/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminContactMessagesRoute =
  AuthenticatedAdminContactMessagesRouteImport.update({
    id: '/admin/contact-messages',
    path: '/admin/contact-messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/admin/content',
    path: '/admin/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminCoreTeamRoute =
  AuthenticatedAdminCoreTeamRouteImport.update({
    id: '/admin/core-team',
    path: '/admin/core-team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/admin/events',
    path: '/admin/events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminJoinApplicationsRoute =
  AuthenticatedAdminJoinApplicationsRouteImport.update({
    id: '/admin/join-applications',
    path: '/admin/join-applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/admin/members',
    path: '/admin/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/admin/messages',
    path: '/admin/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminVolunteersRoute =
  AuthenticatedAdminVolunteersRouteImport.update({
    id: '/admin/volunteers',
    path: '/admin/volunteers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/core-team': typeof CoreTeamRoute
  '/events': typeof EventsRouteWithChildren
  '/events/': typeof EventsIndexRoute
  '/join': typeof JoinRoute
  '/members': typeof MembersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/login': typeof AdminLoginRoute
  '/events/$id': typeof EventsIdRoute
  '/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/contact-messages': typeof AuthenticatedAdminContactMessagesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/core-team': typeof AuthenticatedAdminCoreTeamRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/join-applications': typeof AuthenticatedAdminJoinApplicationsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/core-team': typeof CoreTeamRoute
  '/events': typeof EventsIndexRoute
  '/join': typeof JoinRoute
  '/members': typeof MembersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/login': typeof AdminLoginRoute
  '/events/$id': typeof EventsIdRoute
  '/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/contact-messages': typeof AuthenticatedAdminContactMessagesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/core-team': typeof AuthenticatedAdminCoreTeamRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/join-applications': typeof AuthenticatedAdminJoinApplicationsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/core-team': typeof CoreTeamRoute
  '/events': typeof EventsRouteWithChildren
  '/events/': typeof EventsIndexRoute
  '/join': typeof JoinRoute
  '/members': typeof MembersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/login': typeof AdminLoginRoute
  '/events/$id': typeof EventsIdRoute
  '/_authenticated/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/contact-messages': typeof AuthenticatedAdminContactMessagesRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/core-team': typeof AuthenticatedAdminCoreTeamRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/join-applications': typeof AuthenticatedAdminJoinApplicationsRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/auth'
    | '/contact'
    | '/core-team'
    | '/events'
    | '/events/'
    | '/join'
    | '/members'
    | '/reset-password'
    | '/sitemap.xml'
    | '/volunteer'
    | '/admin/login'
    | '/events/$id'
    | '/admin/activities'
    | '/admin/applications'
    | '/admin/contact-messages'
    | '/admin/content'
    | '/admin/core-team'
    | '/admin/events'
    | '/admin/join-applications'
    | '/admin/members'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/volunteers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/auth'
    | '/contact'
    | '/core-team'
    | '/events'
    | '/join'
    | '/members'
    | '/reset-password'
    | '/sitemap.xml'
    | '/volunteer'
    | '/admin/login'
    | '/events/$id'
    | '/admin/activities'
    | '/admin/applications'
    | '/admin/contact-messages'
    | '/admin/content'
    | '/admin/core-team'
    | '/admin/events'
    | '/admin/join-applications'
    | '/admin/members'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/volunteers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/activities'
    | '/auth'
    | '/contact'
    | '/core-team'
    | '/events'
    | '/events/'
    | '/join'
    | '/members'
    | '/reset-password'
    | '/sitemap.xml'
    | '/volunteer'
    | '/admin/login'
    | '/events/$id'
    | '/_authenticated/admin/activities'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/contact-messages'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/core-team'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/join-applications'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/volunteers'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CoreTeamRoute: typeof CoreTeamRoute
  EventsRoute: typeof EventsRouteWithChildren
  JoinRoute: typeof JoinRoute
  MembersRoute: typeof MembersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VolunteerRoute: typeof VolunteerRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-team': {
      id: '/core-team'
      path: '/core-team'
      fullPath: '/core-team'
      preLoaderRoute: typeof CoreTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/activities': {
      id: '/_authenticated/admin/activities'
      path: '/admin/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AuthenticatedAdminActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contact-messages': {
      id: '/_authenticated/admin/contact-messages'
      path: '/admin/contact-messages'
      fullPath: '/admin/contact-messages'
      preLoaderRoute: typeof AuthenticatedAdminContactMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/core-team': {
      id: '/_authenticated/admin/core-team'
      path: '/admin/core-team'
      fullPath: '/admin/core-team'
      preLoaderRoute: typeof AuthenticatedAdminCoreTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/join-applications': {
      id: '/_authenticated/admin/join-applications'
      path: '/admin/join-applications'
      fullPath: '/admin/join-applications'
      preLoaderRoute: typeof AuthenticatedAdminJoinApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/volunteers': {
      id: '/_authenticated/admin/volunteers'
      path: '/admin/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AuthenticatedAdminVolunteersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminActivitiesRoute: typeof AuthenticatedAdminActivitiesRoute
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminContactMessagesRoute: typeof AuthenticatedAdminContactMessagesRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminCoreTeamRoute: typeof AuthenticatedAdminCoreTeamRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminJoinApplicationsRoute: typeof AuthenticatedAdminJoinApplicationsRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminVolunteersRoute: typeof AuthenticatedAdminVolunteersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminActivitiesRoute: AuthenticatedAdminActivitiesRoute,
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminContactMessagesRoute:
    AuthenticatedAdminContactMessagesRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminCoreTeamRoute: AuthenticatedAdminCoreTeamRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminJoinApplicationsRoute:
    AuthenticatedAdminJoinApplicationsRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminVolunteersRoute: AuthenticatedAdminVolunteersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CoreTeamRoute: CoreTeamRoute,
  EventsRoute: EventsRouteWithChildren,
  JoinRoute: JoinRoute,
  MembersRoute: MembersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VolunteerRoute: VolunteerRoute,
  AdminLoginRoute: AdminLoginRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
